export { map } from "./map";
export { filter } from "./filter";
export {reduce} from "./reduce";
export{reduceRight} from "./reduceRight";
 export {some} from "./some";
 export {every} from "./every";
 export {findByPredicate} from "./findByPredicate";
 export {findByKeyValue} from "./findByKeyValue";
// export * from "./pluck";
// export * from "./lens";